### ISSUE TITLE
Only showing empty table view

### ISSUE THREAD

**Issue by grantfwilkinson** [ygini/EstimoteEditor#2]
Hi I am trying to discover my estimote hardware device and I am assuming that it would show up in the table view when the app first launches, however nothing is displaying on the screen with my device right next to it.  Is there anything you can think of to fix this?  I am needing to update the device firmware, however it is not being discovered at all.  I am using the latest SDK, is that an issue?  Thanks

**Comment by ygini** [comment]
EstimoteEditor seems to work in many place, that's wired.

Do you see your beacon with other apps like demo app from Estimote or apps like BLExplr ?
